os: linux
dist: focal

language: go
go:
  - "1.25.0"

arch:
- amd64

env:
- GO111MODULE=on CGO_ENABLED=1

install:
  - go mod tidy -v

before_install:
  - whereis gcc
  - go env

script:
  - go build -o doc_linux_amd64 -ldflags "-w"
  - cp configs/app.conf.example configs/app.conf
  - ./doc_linux_amd64 version
  - rm configs/app.conf

before_deploy:
  - go mod tidy -v && GOARCH=amd64 GOOS=linux go build -o doc_linux_amd64 -ldflags="-w -X 'git.itopcms.com/jackliu/doc/conf.VERSION=$TRAVIS_TAG' -X 'git.itopcms.com/jackliu/doc/conf.BUILD_TIME=`date`' -X 'git.itopcms.com/jackliu/doc/conf.GO_VERSION=`go version`'"
  # remove files
  - rm appveyor.yml docker-compose.yml Dockerfile .travis.yml .gitattributes .gitignore go.mod go.sum main.go README.md simsun.ttc start.sh
  # remove dirs
  - rm -rf cache commands controllers converter .git .github graphics mail models routers utils
  - ls -alh
  - cp configs/app.conf.example configs/app.conf
  - zip -r doc_linux_amd64.zip configs static uploads views lib doc_linux_amd64 favicon.ico LICENSE.md

deploy:
  provider: releases
  token: $CI_USER_TOKEN
  cleanup: true
  overwrite: true
  file:
    - doc_linux_amd64.zip
  on:
    tags: true
    branch: master
