version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
stack: go 1.25
clone_folder: c:\gopath\src\git.itopcms.com\jackliu\doc
init:
- cmd: >-
    if [%tbs_arch%]==[x86] SET PATH=C:\MinGW\bin;%PATH%
    if [%tbs_arch%]==[x64] SET PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
    SET PATH=%GOPATH%\bin;%GOBIN%;%PATH%
    FOR /f "delims=" %%i IN ('go version') DO (SET GO_VERSION=%%i)
environment:
  GOPATH: c:\gopath
  GOBIN: c:\gobin
  GO111MODULE: on
  CGO_ENABLED: 1
  matrix:
  - tbs_arch: x86
    GOARCH: 386
  - tbs_arch: x64
    GOARCH: amd64
install:
- cmd: >-
    echo %PATH%
    echo %GO_VERSION%
    go env
    where gcc
    where g++
build_script:
- cmd: >-
    cd c:\gopath\src\git.itopcms.com\jackliu\doc
    go mod tidy
    go build -ldflags "-w" -o doc_build_probe.exe ./cmd/doc
    go build -v -o "doc_windows_%GOARCH%.exe" -ldflags="-w -X git.itopcms.com/jackliu/doc/internal/config.VERSION=%APPVEYOR_REPO_TAG_NAME% -X 'git.itopcms.com/jackliu/doc/internal/config.BUILD_TIME=%date% %time%' -X 'git.itopcms.com/jackliu/doc/internal/config.GO_VERSION=%GO_VERSION%'" ./cmd/doc
    7z a -t7z -r doc_windows_%GOARCH%.7z conf/*.conf* conf/lang/* web/* doc_windows_%GOARCH%.exe uploads/*
test_script:
- cmd: >-
    cd c:\gopath\src\git.itopcms.com\jackliu\doc
    xcopy conf\app.conf.example conf\app.conf /F /Y
    doc_windows_%GOARCH%.exe version
deploy: off
